//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmongUsSpecimen.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AmongUsSpecimen.Resources.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom cosmetics update.
        /// </summary>
        internal static string CustomCosmeticsDownloadNotificationTitle {
            get {
                return ResourceManager.GetString("CustomCosmeticsDownloadNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to files remaining.
        /// </summary>
        internal static string CustomCosmeticsFilesRemaining {
            get {
                return ResourceManager.GetString("CustomCosmeticsFilesRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paused.
        /// </summary>
        internal static string CustomCosmeticsPaused {
            get {
                return ResourceManager.GetString("CustomCosmeticsPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause download.
        /// </summary>
        internal static string CustomCosmeticsPauseDownload {
            get {
                return ResourceManager.GetString("CustomCosmeticsPauseDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume download.
        /// </summary>
        internal static string CustomCosmeticsResumeDownload {
            get {
                return ResourceManager.GetString("CustomCosmeticsResumeDownload", resourceCulture);
            }
        }
    }
}
